
obj-$(CONFIG_ALUCARD_CONTROL) 	  += alucard_hotplug.o
obj-$(CONFIG_THUNDERPLUG_CONTROL) += thunderplug.o
obj-$(CONFIG_ALUCARD_CONTROL) 		+= alucard_hotplug.o
obj-$(CONFIG_MSM_HOTPLUG)       += msm_hotplug.o
